# Generated by Django 6.0 on 2026-01-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='education',
            old_name='title',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='period',
            new_name='location',
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='year',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
