# Generated by Django 6.0 on 2026-01-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='updates/'),
        ),
        migrations.AddField(
            model_name='update',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='update',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
