# Generated by Django 6.0 on 2026-01-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_update_featured_image_update_slug_update_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='slug',
            field=models.SlugField(blank=True, default='temp-slug', max_length=250, unique=True),
        ),
    ]
