# Generated by Django 6.0 on 2026-01-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_alter_update_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
