# Generated by Django 6.0 on 2026-01-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0004_alter_update_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (max 160 characters)', max_length=160),
        ),
    ]
